RTI-2194 Разработать туду лист
Executioner34/ToDo pull request #1
Opened 2023-01-23 07:14 UTC by Executioner34

# Функциональные изменения

- Разработан туду лист с фильтрами
- Задачи хранятся в localStorage
- Работа с localStorage осуществляется через апи и стор

https://track.ratio.digital/youtrack/issue/RTI-2194/Razrabotat-tudu-list

2023-01-23 09:27 UTC, Denis-Str requested changes
23.01

2023-01-23 09:27 UTC, Denis-Str commented on pages/todo/_id.vue
> +      return this.$store.getters["tasks/textIDTask"](Number(this.$route.params.id))
textIDTask - перевод - задача текстового идентификатора?))
название метода taskText в сторе textIDTask :)

2023-01-23 09:27 UTC, Denis-Str commented on store/tasks/index.js
> +
где дока?) что тут происходит)

2023-01-23 09:27 UTC, Denis-Str commented on store/tasks/index.js
> +  filteredTask: (state) => {
Task - это задача, а у тебя массив задач, поэтому tasks

2023-01-23 09:27 UTC, Denis-Str commented on store/tasks/index.js
> +    if (state.currentFilter === 'active') {
тут бы я сделал через switch/case

2023-01-23 09:27 UTC, Denis-Str commented on store/tasks/index.js
> +  SET_TASKS: (state, payload) => {
почему тут появились стрелочные функции?

2023-01-23 09:27 UTC, Denis-Str commented on store/tasks/index.js
> +    state.taskCounter += 1
какую функцию выполняет каунтер тут?

2023-01-24 18:36 UTC, Executioner34 commented on components/views/index/FiltersList/index.vue
> +        :checked="activeFilter === item.name"
Исправил

2023-01-24 18:37 UTC, Executioner34 commented on components/CheckBox/index.vue
> +  <div class="check-box-component">
Изменил чекбокс на ратио.

2023-01-24 18:38 UTC, Executioner34 commented on components/views/index/FiltersList/index.vue
> +    <li v-for="(item, ind) in filters" :key="ind" class="item">
Исправил

2023-01-24 18:39 UTC, Executioner34 commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +  <div class="task-item-component">
Исправил на линк `<a>`. На `<nuxt-link>` не получилось повесить свой обработчик(

2023-01-24 18:41 UTC, Executioner34 commented on components/views/index/FiltersList/index.vue
> +    this.$store.commit('tasks/SET_CURRENT_FILTER', this.activeFilter)
Исправил на **selectedFilter**

2023-01-24 18:41 UTC, Executioner34 commented on components/views/index/FiltersList/index.vue
> +  .item:not(:last-child) {
Исправил

2023-01-24 18:42 UTC, Executioner34 commented on components/views/index/TaskItemsList/index.vue
> +    <li v-for="task in tasks" :key="task.id">
Исправил

2023-01-24 18:42 UTC, Executioner34 commented on api/LocalStorage/index.js
> +class LocalStorage {
Исправил на функции, добавил документацию

2023-01-24 18:43 UTC, Executioner34 commented on components/CheckBox/index.vue
> +      validator: (value) => ['checkbox', 'radio'].includes(value)
Удалил компонент **CheckBox**

2023-01-24 18:43 UTC, Executioner34 commented on components/CheckBox/index.vue
> +    checked: {
Исправил

2023-01-24 18:44 UTC, Executioner34 commented on components/CheckBox/index.vue
> + * @desc компонент чекбокса или радио инпута в зависимости от пропса
Исправил

2023-01-24 18:44 UTC, Executioner34 commented on components/CheckBox/index.vue
> +    onClick() {
Исправил названия обработчиков событий

2023-01-24 18:45 UTC, Executioner34 commented on components/views/index/AddTask/index.vue
> + * @vue-computed {Number} lastID - id последней задачи
Для id следующей задачи. Изменил название на **nextFreeID**

2023-01-24 18:46 UTC, Executioner34 commented on components/views/index/AddTask/index.vue
> +  <div class="add-task-component">
Исправил

2023-01-24 18:46 UTC, Executioner34 commented on pages/index.vue
> +    <add-task class="add"/>
Исправил

2023-01-24 18:52 UTC, Executioner34 commented on components/views/index/AddTask/index.vue
> +  <div class="add-task-component">
Данный компонент выполняет действия со стором. Можно конечно и в родительском это сделать, но при маштабировании проекта все равно придется декомпозировать логику работы со стором. Выбрал компромисс удалить компонент **TheInput**

2023-01-24 18:54 UTC, Executioner34 commented on pages/index.vue
> +    <add-task class="add"/>
Удалил компонент `TheInput`

2023-01-24 18:55 UTC, Executioner34 commented on pages/todo/_id.vue
> +      return this.$store.getters["tasks/textIDTask"](Number(this.$route.params.id))
Исправил на `textTask`

2023-01-24 18:55 UTC, Executioner34 commented on store/tasks/index.js
> +
Добавил документацию

2023-01-24 18:55 UTC, Executioner34 commented on store/tasks/index.js
> +  filteredTask: (state) => {
Исправил

2023-01-24 18:56 UTC, Executioner34 commented on store/tasks/index.js
> +    if (state.currentFilter === 'active') {
Исправил

2023-01-24 18:56 UTC, Executioner34 commented on store/tasks/index.js
> +  SET_TASKS: (state, payload) => {
Исправил)

2023-01-24 18:57 UTC, Executioner34 commented on store/tasks/index.js
> +    state.taskCounter += 1
Удалил `counter`.

2023-01-25 07:43 UTC, Denis-Str requested changes
25.01

2023-01-25 07:43 UTC, Denis-Str commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +    <a class="link" @click="onLink">
почему не nuxt-link?

2023-01-25 07:43 UTC, Denis-Str commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +      <button ref="toggle" class="btn btn--complete" @click="toggleHandler">
это не верно тут должен быть чекбокс, а тут кнопка. Какой то пседо чекбокс

2023-01-25 07:43 UTC, Denis-Str commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +    classText() {
это не информативно, на сколько я понял тут ты вешаешь стиль типа завершенной задачи, значит стиль относится к модификатору - так и назови "isCompleted"
это оп сути "флаг" по нему переключается стиль

2023-01-25 07:43 UTC, Denis-Str commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +      <span class="text" :class="classText">{{ textTask }}</span>
в данном случае стили можно объединить, в зависимости от флага либо вкл либо отк стиль
:class=["text", {"text__complite: isCompleted"}]

2023-01-25 07:43 UTC, Denis-Str commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +    onLink(event) {
что тут происходит? я так понимаю на всплытие событий напоролся?))
читал про это 
https://v3.ru.vuejs.org/ru/guide/events.html#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B8

2023-01-25 07:43 UTC, Denis-Str commented on components/views/index/TaskItemsList/index.vue
> +    IDToString(num) {
документация методо делаем так (пример)
    /**
     * метод открывает модальное окно со списком сопутствующих услуг
     * по умолчанию тип 'order', еще может быть 'edit' их надо задавать ключ,
     * что бы отличить, где оформление, где редактирование
     */

2023-01-25 07:43 UTC, Denis-Str commented on layouts/default.vue
> +<template>
в задаче лейату не нужны, это так к слову
по умолочанию у накста и так есть default-layout

2023-01-25 07:43 UTC, Denis-Str commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +      if (isAnyButton) {
можно короче
      if (isAnyButton) return

2023-01-25 07:43 UTC, Denis-Str commented on store/tasks/index.js
> + * @desc - tasks - массив задач. selectedFilter - выбранный фильтр. nextFreeID - свободное id для таски
все в одну строчку, это не верно надо по отдельности

2023-01-25 07:43 UTC, Denis-Str commented on pages/todo/_id.vue
> +    taskText() {
на будущие и для информации, в таких случаях обычно берут id (или любой другой ключ, в зависимости от спецификации бэка) из роута и по нему делают запрос на бэк для получения данных, для страницы поста, статьи и тд 
от бэка приходит запрос, его уже закидываем в стор и берем данные от дуда

2023-01-25 07:43 UTC, Denis-Str commented on store/tasks/index.js
> +  DELETE_TASK(state, id) {
мутация должна быть простой и без логики, это по факту диспатч
т.е. вызываем диспатч на основе айди делаем новый массим и уже комитим его с помощью SET_TASKS

мутации по факту не делают ни каких действий, они только устанавливают данные

есть проще кейс как удалить из массива элемент, отфильтровываем массив по айдишнику
 const ind = state.tasks.filter((task) => task.id !== id)

2023-01-25 07:44 UTC, Denis-Str commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +  <div class="task-item-component">
надо повесить

2023-01-25 07:45 UTC, Denis-Str commented on components/CheckBox/index.vue
> +      validator: (value) => ['checkbox', 'radio'].includes(value)
а зря)) у тебя и чекбоксы есть и ратио

2023-01-25 20:17 UTC, Executioner34 commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +    <a class="link" @click="onLink">
Исправил на nuxt-link

2023-01-25 20:17 UTC, Executioner34 commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +      <button ref="toggle" class="btn btn--complete" @click="toggleHandler">
Вернул `CheckBox`

2023-01-25 20:18 UTC, Executioner34 commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +    classText() {
Переименовал

2023-01-25 20:18 UTC, Executioner34 commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +      <span class="text" :class="classText">{{ textTask }}</span>
Переписал

2023-01-25 20:19 UTC, Executioner34 commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +    onLink(event) {
Да, я не в ту сторону копал. Хотел на nuxt-link повесить свой обработчик)

2023-01-25 20:20 UTC, Executioner34 commented on components/views/index/TaskItemsList/index.vue
> +    IDToString(num) {
Задокументировал все методы в проекте

2023-01-25 20:23 UTC, Executioner34 commented on layouts/default.vue
> +<template>
А если я хочу ограничить ширину дефолтного лайаута? Это в global.scss делать?

2023-01-25 20:23 UTC, Executioner34 commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +      if (isAnyButton) {
Пофиксил)

2023-01-25 20:24 UTC, Executioner34 commented on store/tasks/index.js
> + * @desc - tasks - массив задач. selectedFilter - выбранный фильтр. nextFreeID - свободное id для таски
Исправил

2023-01-25 20:25 UTC, Executioner34 commented on pages/todo/_id.vue
> +    taskText() {
Понял)

2023-01-25 20:25 UTC, Executioner34 commented on store/tasks/index.js
> +  DELETE_TASK(state, id) {
Вынес логику из мутаций

2023-01-26 07:10 UTC, Denis-Str commented on layouts/default.vue
> +<template>
думаю да, не сталкивался с таким)

2023-01-26 07:42 UTC, Denis-Str requested changes
26.01

2023-01-26 07:42 UTC, Denis-Str commented on components/common/CheckBox/index.vue
> +    :checked="checked"
где v-model?

2023-01-26 07:42 UTC, Denis-Str commented on components/views/index/FiltersList/index.vue
> +    selectedFilter: function (newName, oldName) {
1. selectedFilter(newName, oldName) в данном контексте без function
2. oldName - не используешь, зачем тогда оно

когда вешаешь вотчер на ключи объекта тогда function

```
watch: {
  'good.id': function(value) {
    console.log(value)
  }
}
```

2023-01-26 07:42 UTC, Denis-Str commented on components/views/index/FiltersList/index.vue
> +<template>
не так логика тут организована, все из за того, что ты не верно сделал ратио. Тут даже ратио не нужна, это обычная кнопка
логика такая:
есть радио кнопка, каждая кнопка хранит свой фильтр, при клике на кнопку у тебя дальше 2 пути либо эмитить в родителя событие и передать данные, либо (что лучше) записть выбранный фильтр в стор, тогда он будет у тебя доступен в любом месте

2023-01-26 07:42 UTC, Denis-Str commented on components/views/index/FiltersList/index.vue
> +      this.$store.commit('tasks/SET_SELECTED_FILTER', newName)
тут тоже намудрил) в стор записал и в дату компоненте, т.е. одно и тоже состояние ты хранишь в двух местах

2023-01-26 07:42 UTC, Denis-Str commented on components/common/RadioInput/index.vue
> +      return this.current === this.value
вот тут как раз тянем из стора выбранный фильтр и сравниваем со значением

2023-01-26 07:42 UTC, Denis-Str commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +      <check-box :checked="complete" class="checkbox" @click.native.stop="checkBoxHandler"/>
click.native.stop? вот ис дас - @change а не @click

2023-01-26 07:42 UTC, Denis-Str commented on layouts/default.vue
> +<template>
лейаут не ограничивают, для этого используют глобальный контейнер

2023-01-26 07:42 UTC, Denis-Str commented on store/tasks/index.js
> +  pullTask({ commit }, data) {
pullTask - перевод - задача вытягивания), тут Task в единственном числе 
Tasks - это множественное число, судя по названию ты обновляешь элемент, но возвращаешь массив
описание - Обновляем задачу ))
updateЧто-то там

2023-01-26 18:04 UTC, Executioner34 commented on components/common/CheckBox/index.vue
> +    :checked="checked"
Исправил

2023-01-26 18:05 UTC, Executioner34 commented on components/common/CheckBox/index.vue
> +export default {
Исправил

2023-01-26 18:07 UTC, Executioner34 commented on components/common/RadioInput/index.vue
> +<template>
Из за того, что чекбокс внутри nuxt-link, то перехватывать только событие клик получалось.

2023-01-26 18:08 UTC, Executioner34 commented on components/views/index/FiltersList/index.vue
> +    selectedFilter: function (newName, oldName) {
Исправил

2023-01-26 18:08 UTC, Executioner34 commented on components/views/index/FiltersList/index.vue
> +<template>
Переписал

2023-01-26 18:08 UTC, Executioner34 commented on components/views/index/FiltersList/index.vue
> +      this.$store.commit('tasks/SET_SELECTED_FILTER', newName)
Исправил)

2023-01-26 18:09 UTC, Executioner34 commented on components/common/RadioInput/index.vue
> +      return this.current === this.value
И это)

2023-01-26 18:10 UTC, Executioner34 commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +      <check-box :checked="complete" class="checkbox" @click.native.stop="checkBoxHandler"/>
Из за того, что чекбокс внутри nuxt-link, то перехватывать только событие клик получалось. В родительском компоненте слушаем событие update-checkbox

2023-01-26 18:11 UTC, Executioner34 commented on store/tasks/index.js
> +  pullTask({ commit }, data) {
Изменил название метода

2023-01-27 07:37 UTC, Denis-Str requested changes
27.01

2023-01-27 07:37 UTC, Denis-Str commented on assets/scss/global.scss
> +#__nuxt {
контейнер для этого, делается глобальный я вроде написал - типа app-container
ну на будущие, в общем не надо так делать

2023-01-27 07:37 UTC, Denis-Str commented on components/common/CheckBox/index.vue
> +    v-model="model"
checked, а не model
для правильности и читаемости

2023-01-27 07:37 UTC, Denis-Str commented on components/common/CheckBox/index.vue
> +      model: false,
checked

2023-01-27 07:37 UTC, Denis-Str commented on components/common/CheckBox/index.vue
> +      this.$emit('update-checkbox', ev.target.checked)
тут не нужен ev.target.checked, тут this.checked
при чеку отработает v-model и изменит состояние checked в data

а вот когда идет ввод в инпут, там уже через эвент

2023-01-27 07:37 UTC, Denis-Str commented on components/common/CheckBox/index.vue
> +export default {
практически исправил )

2023-01-27 07:37 UTC, Denis-Str commented on components/common/RadioInput/index.vue
> +<template>
в пнд вместе перепишем
я где писал, тут не нужны ратио, это обычная кнопка

2023-01-27 07:37 UTC, Denis-Str commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +      <button class="btn" @click.stop.prevent="deleteHandler">❌</button>
у кнопки ты не указал type, если я не ошибаюсь по умолчанию у тебя тип submit, те при клике кнопка перезагружает страницу и пытается отправить данные поэтому 
<button type="button" class="btn" @click.stop="deleteHandler">
@click.stop скорее всего можно заменить на @click.self

2023-01-27 14:50 UTC, Executioner34 commented on assets/scss/global.scss
> +#__nuxt {
Исправил

2023-01-27 14:52 UTC, Executioner34 commented on components/common/CheckBox/index.vue
> +    v-model="model"
Переименовал model на checked, а пропс checked на value

2023-01-27 14:52 UTC, Executioner34 commented on components/common/CheckBox/index.vue
> +      model: false,
Исправил

2023-01-27 14:54 UTC, Executioner34 commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +      <button class="btn" @click.stop.prevent="deleteHandler">❌</button>
Изменил на @click.self.prevent . Без prevent все равно браузер пытается перезагрузить страницу

2023-01-30 04:28 UTC, Denis-Str approved these changes

2023-01-30 04:28 UTC, Denis-Str commented on components/views/index/TaskItemsList/TaskItem/index.vue
> +      <button type="button" class="btn" @click.self.prevent="deleteHandler">
с точки зрения верстки кнопку надо было вынести за nuxt-link
она не относится к ссылке

2023-01-30 04:32 UTC, merged